[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  01:51:33Z

App                      Version  Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application               active       1  postgresql-test-app  latest/edge    257  10.152.183.24   no       received database credentials of the first database
another-data-integrator           waiting      1  data-integrator      latest/stable   40  10.152.183.152  no       installing agent
another-database         14.13    active       3  postgresql-k8s                        1  10.152.183.116  no       
data-integrator                   waiting      1  data-integrator      latest/stable   40  10.152.183.146  no       installing agent
database                 14.13    active       3  postgresql-k8s                        0  10.152.183.66   no       
postgresql-test-app               active       2  postgresql-test-app  latest/edge    257  10.152.183.196  no       received database credentials of the first database

Unit                        Workload  Agent  Address       Ports  Message
another-application/0*      active    idle   10.1.236.150         received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.236.154         Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.236.147         Primary
another-database/1          active    idle   10.1.236.149         
another-database/2          active    idle   10.1.236.148         
data-integrator/0*          blocked   idle   10.1.236.153         Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.236.146         Primary
database/1                  active    idle   10.1.236.152         
database/2                  active    idle   10.1.236.151         
postgresql-test-app/0       active    idle   10.1.236.136         received database credentials of the first database
postgresql-test-app/1*      active    idle   10.1.236.137         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-database-0: 01:40:56 ERROR unit.database/0.juju-log Kubernetes service get failed: services "database" not found
unit-database-0: 01:40:56 ERROR unit.database/0.juju-log Kubernetes service patch failed: services "database" not found
unit-database-0: 01:41:19 ERROR unit.database/0.juju-log Kubernetes service get failed: services "database" not found
unit-database-0: 01:41:19 ERROR unit.database/0.juju-log Kubernetes service patch failed: services "database" not found
unit-database-0: 01:47:04 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "aadf417b-c004-4bc9-824d-e759d185cbf6:r#16#postgresql-test-app": settings aadf417b-c004-4bc9-824d-e759d185cbf6:r#16#postgresql-test-app not found (not found)
unit-database-2: 01:47:05 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "aadf417b-c004-4bc9-824d-e759d185cbf6:r#16#postgresql-test-app": settings aadf417b-c004-4bc9-824d-e759d185cbf6:r#16#postgresql-test-app not found (not found)
unit-database-0: 01:50:28 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 01:50:28 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 244, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 01:50:29 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 01:50:29 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 244, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...