[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  02:06:34Z

App                      Version  Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application               active       1  postgresql-test-app  latest/edge    181  10.152.183.57   no       received database credentials of the first database
another-data-integrator           waiting      1  data-integrator      latest/stable   26  10.152.183.182  no       installing agent
another-database         14.12    active       3  postgresql-k8s                        0  10.152.183.37   no       
data-integrator                   waiting      1  data-integrator      latest/stable   26  10.152.183.179  no       installing agent
database                 14.12    active       3  postgresql-k8s                        1  10.152.183.60   no       
postgresql-test-app               active       2  postgresql-test-app  latest/edge    181  10.152.183.221  no       received database credentials of the first database

Unit                        Workload  Agent  Address       Ports  Message
another-application/0*      active    idle   10.1.236.150         received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.236.154         Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.236.143         Primary
another-database/1          active    idle   10.1.236.144         
another-database/2          active    idle   10.1.236.145         
data-integrator/0*          blocked   idle   10.1.236.153         Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.236.147         Primary
database/1                  active    idle   10.1.236.152         
database/2                  active    idle   10.1.236.151         
postgresql-test-app/0*      active    idle   10.1.236.136         received database credentials of the first database
postgresql-test-app/1       active    idle   10.1.236.137         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-database-0: 02:04:50 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 02:04:50 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 228, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 02:04:52 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 02:04:52 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 228, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 02:05:19 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "9b339ab1-ca4e-44d8-89fe-06a559ce7a31:r#20#data-integrator": settings 9b339ab1-ca4e-44d8-89fe-06a559ce7a31:r#20#data-integrator not found (not found)
unit-database-2: 02:05:20 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "9b339ab1-ca4e-44d8-89fe-06a559ce7a31:r#20#data-integrator": settings 9b339ab1-ca4e-44d8-89fe-06a559ce7a31:r#20#data-integrator not found (not found)

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...